version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql-data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=artemis
