version: '3.9'

networks:
  hazelcast-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql-data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=artemis
    networks:
      hazelcast-net:
        ipv4_address: 172.30.0.7


  registry:
    image: jhipster/jhipster-registry:latest
    ports:
      - '8761:8761'
    environment:
      SPRING_PROFILES_ACTIVE: prod # TODO: Is this necessary
      EUREKA_INSTANCE_HOSTNAME: registry # advertise as “registry”, not localhost
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:admin@registry:8761/eureka/
      JHIPSTER_REGISTRY_PASSWORD: admin
      JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET: "zhK6YPbfcOsNVw5QYtRQ1LCcnot+E/+ewbQgzV8gvpUwxwj/zeeDaxISqVSTWjG7bnWIQaefuaU+9NWz9ALG5w=="
    networks:
      hazelcast-net:
        ipv4_address: 172.30.0.8


  message-broker-for-websockets:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - '61616:61616'
      - '61613:61613' # STOMP (Simple Text Oriented Messaging Protocol)
      - '8161:8161'
    networks:
      hazelcast-net:
        ipv4_address: 172.30.0.9


  artemis-main-instance:
    image: ghcr.io/ls1intum/artemis:8.1.3
    ports:
      # The REST Apis, Website etc.
      - '8080:8080'
    depends_on:
      - postgres
      - registry
      - message-broker-for-websockets
    volumes:
      - ./files/main-instance/application-local.yml:/opt/artemis/config/application-local.yml:ro
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/opt/artemis/config/application-local.yml"
      SPRING_PROFILES_ACTIVE: "prod,core,localvc,localci,docker,local"
      SERVER_PORT: 8080
    networks:
      hazelcast-net:
        ipv4_address: 172.30.0.10

  artemis-main-instance-2:
    image: ghcr.io/ls1intum/artemis:8.1.3
    ports:
      # The REST Apis, Website etc.
      - '8082:8080'
    depends_on:
      - postgres
      - registry
      - message-broker-for-websockets
    volumes:
      - ./files/main-instance-2/application-local.yml:/opt/artemis/config/application-local.yml:ro
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/opt/artemis/config/application-local.yml"
      SPRING_PROFILES_ACTIVE: "prod,core,localvc,localci,docker,local,scheduling"
      SERVER_PORT: 8080
    networks:
      hazelcast-net:
        ipv4_address: 172.30.0.12

  artemis-build-agent-1:
    image: ghcr.io/ls1intum/artemis:8.1.3
    ports:
      # The REST Apis, Website etc.
      - '8081:8080'
    depends_on:
      - artemis-main-instance
    volumes:
      - ./files/build-agent-1/application-local.yml:/opt/artemis/config/application-local.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock # Host docker is available for the build agent.
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/opt/artemis/config/application-local.yml"
      SPRING_PROFILES_ACTIVE: "prod,buildagent"
      SERVER_PORT: 8080
    group_add:
      - "${DOCKER_GROUP_ID}" # Allow access to /var/run/docker.sock.
    networks:
      hazelcast-net:
        ipv4_address: 172.30.0.11
