info:
    contact: meMySelf@and.i.de
    operatorName: Myself And I
    operatorAdminName: Me and Myself

logging:
  level:
    com.hazelcast: TRACE      # specifically see all Hazelcast internals
    com.netflix.discovery: TRACE  # Eureka client internals

artemis:
    user-management:
        use-external: false
        internal-admin:
            username: artemis_admin
            password: artemis_admin

    version-control:
        url: "http://artemis-core-instance:8080"
        default-branch: main
        user: artemis_vc_user
        password: artemis_vc_password
        build-agent-git-username: buildjob_user
        build-agent-git-password: buildjob_password

    git:
        name:  "Artemis LocalVC"        # resolves ${artemis.git.name}
        email: "git@localhost"          # resolves ${artemis.git.email}
        password: "someGitPassword"     # resolves ${artemis.git.password}

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: "zhK6YPbfcOsNVw5QYtRQ1LCcnot+E/+ewbQgzV8gvpUwxwj/zeeDaxISqVSTWjG7bnWIQaefuaU+9NWz9ALG5w=="

eureka:
    client:
        enabled: true
        service-url:
            defaultZone: http://admin:admin@registry:8761/eureka/

    instance:
        prefer-ip-address: true
        ip-address: 192.168.2.116
        appname: artemis
        instanceId: Artemis:core1

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://postgres:5432/artemis
        username: postgres
        password: postgres
        hikari:
            poolName: Hikari
            auto-commit: false
    hazelcast:
        interface: 172.30.0.10

hazelcast:
    network:
        public-address: 192.168.2.116:5701 # ensures reconnects work after a connection was dropped temporarily
        join:
            eureka:
                enabled: true
            multicast:
                enabled: false
            tcp-ip:
                enabled: false
