info:
    contact: meMySelf@and.i.de
    operatorName: Myself And I
    operatorAdminName: Me and Myself

logging:
  level:
    com.hazelcast: TRACE      # specifically see all Hazelcast internals
    com.netflix.discovery: TRACE  # Eureka client internals

artemis:
    continuous-integration:
        docker-connection-uri: unix:///var/run/docker.sock
        specify-concurrent-builds: true                     # Set to false, if the number of concurrent build jobs should be chosen automatically based on system resources
        concurrent-build-size: 1                            # If previous value is true: Set to desired value but keep available system resources in mind
        asynchronous: true
        build-container-prefix: local-ci-
        image-cleanup:
            enabled: true                                   # If set to true (recommended), old Docker images will be deleted on a schedule.
            expiry-days: 2                                  # The number of days since the last use after which a Docker image is considered outdated and can be removed.
            cleanup-schedule-time: 0 0 3 * * *              # CRON expression for cleanup schedule
        container-cleanup:
            expiry-minutes: 5                               # Time after a hanging container will automatically be removed
            cleanup-schedule-minutes: 60                    # Schedule for container cleanup
        build-agent:
            short-name: "artemis-build-agent-1"             # Short name of the build agent. This should be unique for each build agent. Only lowercase letters, numbers and hyphens are allowed.
            display-name: "Artemis Build Agent 1"           # The Display name in the Artemis UI.
        build-timeout-seconds:
            max: 240                                        # (Optional, default 240) Maximum time in seconds a build job is allowed to run. If a build job exceeds this time, it will be cancelled.

    git:
        name:  "Artemis LocalVC"
        email: "git@localhost"
        password: "someGitPassword"

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: "zhK6YPbfcOsNVw5QYtRQ1LCcnot+E/+ewbQgzV8gvpUwxwj/zeeDaxISqVSTWjG7bnWIQaefuaU+9NWz9ALG5w=="

eureka:
    client:
        enabled: true
        service-url:
            defaultZone: http://admin:admin@192.168.2.116:8761/eureka/

    instance:
        prefer-ip-address: true
        ip-address: 192.168.2.203
        appname: artemis
        instanceId: Artemis:build1

# spring:
#     hazelcast:
#         interface: 172.30.0.11

hazelcast:
    network:
        public-address: 192.168.2.203:5701
        join:
            eureka:
                enabled: true
            multicast:
                enabled: false
            tcp-ip:
                enabled: false   # ← avoid empty fallback list
